name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Sentry
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: bethel
          SENTRY_PROJECT: platform
        with:
          environment: production
